# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/shangcongrong"
  #weibo: "#"
  #rss: "#"
  zhihu: "http://www.zhihu.com/people/rodriguezxin"
  #douban: "#"
  mail: "yangxin1545@163.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "https://cn.linkedin.com/pub/鑫-杨/b7/243/430"

rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: false
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /avatar.jpg

#你的头像url
avatar: "https://avatars1.githubusercontent.com/u/2649927?v=3&u=8517cc7bbcbac2fea9b631e386b3dd32755b6eb0&s=140"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
#friends:
#  奥巴马的博客: http://localhost:4000/
#  卡卡的美丽传说: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 每一首歌都有一个故事～